project_name: tenta-dns
release:
  github:
    owner: tenta-browser
    name: tenta-dns
  name_template: '{{.Tag}}'
brew:
  commit_author:
    name: tenta-browser
    email: info@tenta.com
  install: bin.install "tenta-dns"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  main: tenta-dns.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: tenta-dns
archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
  - changelog*
  - CHANGELOG*
fpm:
  bindir: /usr/local/bin
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
dockers:
  - image: tenta/tenta-dns
    latest: true
    tag_template: '{{ .Tag }}'